config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get 'signin', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
    get 'signup', to: 'devise/registrations#new'
  end

  get 'feed', to: 'feed#show'

  # get 'users/:username', to: 'users#show', as: 'user'
  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
    end
  end

  resources :items do
    member do
      post 'vote', to: 'votes#create'
      delete 'unvote', to: 'votes#destroy'
    end
  end
  
  resources :links
  resources :tweets

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :content, presence: true, length: { maximum: 180 }

  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_tweet_and_verify_ownership, only: [:edit, :update, :destroy]

  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tweets/1
  def update    
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private

    def find_tweet_and_verify_ownership
      @tweet = Tweet.find(params[:id])
      if @tweet.user != current_user
        redirect_to @tweet, notice: "You aren't allowed to perform this action."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:user_id, :content, :image)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true, html: { multipart: true }) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/tweets/edit.html.erb
<div class="container" id="home-container">
  <h1>Editing Tweet</h1>

  <%= render 'form', tweet: @tweet %>

  <%= link_to 'Show', @tweet %> |
  <%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/index.html.erb
<div class="container" id="home-container">
  <div class="row">  
    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <% if user_signed_in? %>
            <h5 class="card-title"><%= link_to current_user.name, user_path(current_user.username) %></h5>
            <p class="card-text"><%= link_to current_user.username, user_path(current_user.username) %></p>
          <% else %>
            <p class="card-text"><%= link_to "Sign in", signin_path %> or <%= link_to "Sign up", signup_path %> now.</p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <% if user_signed_in? %>
        <%= link_to 'New Tweet', new_tweet_path %>
      <% end %>
      <ul class="list-group">
        <% @tweets.each do |tweet| %>
          <%= link_to tweet, class: "list-group-item list-group-item-action" do %>
              <h5 class="card-title"><%= tweet.user.username %></h5>
              <p class="card-text"><%= tweet.content %></p>
              <% if tweet.image.present? %>
                <center><img class="img-fluid" src=<%= tweet.image %> /></center>
                <br/>
              <% end %>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="container" id="home-container">
  <h1>New Tweet</h1>

  <%= render 'form', tweet: @tweet %>

  <%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/show.html.erb
<div class="container" id="home-container">
  <div class="row">
    <div class="offset-md-2 col-md-8">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= link_to @tweet.user.username, user_path(@tweet.user.username) %></h5>
          <p class="card-text"><%= @tweet.content %></p>
          <% if @tweet.image.present? %>
            <center><img class="img-fluid" src=<%= @tweet.image %> /></center>
            <br/>
          <% end %>
          <% if @tweet.user == current_user %>
            <%= link_to 'Edit', edit_tweet_path(@tweet), class: "card-link" %>
            <%= link_to 'Destroy', @tweet, class: "card-link", method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
          <%= link_to 'Back', tweets_path, class: "card-link" %>
        </div>
      </div>
    </div>
  </div>
</div>