config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get 'signin', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
    get 'signup', to: 'devise/registrations#new'
  end

  get 'feed', to: 'feed#show'

  # get 'users/:username', to: 'users#show', as: 'user'
  resources :users, only: :show, param: :username do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
    end
  end

  resources :items do
    member do
      post 'vote', to: 'votes#create'
      delete 'unvote', to: 'votes#destroy'
    end
  end
  
  resources :links
  resources :tweets

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_link_and_verify_ownership, only: [:edit, :update, :destroy]

  # GET /links
  def index
    @links = Link.all
  end

  # GET /links/1
  def show
    @link = Link.find(params[:id])
  end

  # GET /links/new
  def new
    @link = current_user.links.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  def create
    @link = current_user.links.new(link_params)
    if @link.save
      redirect_to @link, notice: 'Link was successfully created.' 
    else
      render :new
    end
  end

  # PATCH/PUT /links/1
  def update
    if @link.update(link_params)
      redirect_to @link, notice: 'Link was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /links/1
  def destroy
    @link.destroy
    redirect_to links_url, notice: 'Link was successfully destroyed.'
  end

  private

    def find_link_and_verify_ownership
      @link = Link.find(params[:id])
      if @link.user != current_user
        redirect_to @link, notice: "You aren't allowed to perform this action."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:user_id, :url, :title)
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_field :url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/links/edit.html.erb
<div class="container" id="home-container">
  <h1>Editing Link</h1>

  <%= render 'form', link: @link %>

  <%= link_to 'Show', @link %> |
  <%= link_to 'Back', links_path %>
</div>

app/views/links/index.html.erb
<div class="container" id="home-container">
  <h1>Links</h1>

  <table class="table">
    <thead>
      <tr>
        <th>User</th>
        <th>Url</th>
        <th>Title</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @links.each do |link| %>
        <tr>
          <td><%= link.user.username %></td>
          <td><%= link_to link.url, link.url, target: "_blank"  %></td>
          <td><%= link.title %></td>
          <td><%= link_to 'Show', link %></td>
          <% if link.user == current_user %>
            <td><%= link_to 'Edit', edit_link_path(link) %></td>
            <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Link', new_link_path %>

</div>

app/views/links/new.html.erb
<div class="container" id="home-container">
  <h1>New Link</h1>

  <%= render 'form', link: @link %>

  <%= link_to 'Back', links_path %>  
</div>

app/views/links/show.html.erb
<div class="container" id="home-container">
  <p>
    <strong>User:</strong>
    <%= @link.user.username %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= link_to @link.url, @link.url, target: "_blank" %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @link.title %>
  </p>

  <% if @link.user == current_user %>
    <%= link_to 'Edit', edit_link_path(@link) %> |
  <% end %>
  <%= link_to 'Back', links_path %>
</div>